apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox-pod
  name: busybox-pod
spec:
  containers:
  - command:
    - bin/sh
    - -c
    - sleep 3600
    image: busybox
    name: busybox-container-1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
