apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-deploy-cmd
  name: nginx-deploy-cmd
  namespace: ns-dev
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31000
  selector:
    app: nginx-deploy-cmd
  type: NodePort
status:
  loadBalancer: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-deploy-cmd
  name: nginx-deploy-cmd
  namespace: ns-prod
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 32000
  selector:
    app: nginx-deploy-cmd
  type: NodePort
status:
  loadBalancer: {}
